theme: minima
title: Map Your Enthusiasm
author: Sarah Kanee
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Working through geospatial projects for a better understanding of earth.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
